name: Release
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.15.x
#          - 1.16.x
        os:
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  goreleaser:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --parallelism 2 --rm-dist --timeout 1h --release-notes .release_info.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
