name: Release
on:
  workflow_run:
    workflows: 
      - Test
    branches:
      - main
    tags:
      - 'v*'
    types: 
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  goreleaser:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --parallelism 2 --rm-dist --timeout 1h --release-notes .release_info.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
